using MarleneCollectionXmlTool.DBAccessLayer;
using MarleneCollectionXmlTool.DBAccessLayer.Models;
using MarleneCollectionXmlTool.Domain.Queries.SyncProductStocksWithWholesales.Models;
using MarleneCollectionXmlTool.Domain.Services;
using MarleneCollectionXmlTool.Domain.Tests.Utils;
using Xunit;

namespace MarleneCollectionXmlTool.Domain.Tests.Helpers;

public class ProductAttributeServiceTests
{
    private readonly WoocommerceDbContext _dbContext;
    private readonly ProductAttributeService _sut;

    public ProductAttributeServiceTests()
    {
        _dbContext = FakeDbContextFactory.CreateMockDbContext<WoocommerceDbContext>();
        _sut = new ProductAttributeService(_dbContext);
    }

    [Fact]
    public void CreateProductAttributes_SuccessfulySerializedObject()
    {
        //Arrange
        var parentProductDto = new WpPostDto(null, null, null, null, null);
        var variantProductDtos = new List<WpPostDto>
        {
            new WpPostDto(null, "34", null, null, null),
            new WpPostDto(null, "36", null, null, null),
            new WpPostDto(null, "38", null, null, null),
            new WpPostDto(null, "40", null, null, null)
        };

        //Act
        var response = _sut.CreateProductAttributesString(parentProductDto, variantProductDtos);

        //Assert
        Assert.NotNull(response);
        Assert.Equal(
            "a:5:{s:10:\"pa_rozmiar\";a:6:{s:4:\"name\";s:10:\"pa_rozmiar\";s:5:\"value\";s:0:\"\";s:8:\"position\";i:0;s:10:\"is_visible\";i:1;s:12:\"is_variation\";i:1;s:11:\"is_taxonomy\";i:1;}s:8:\"pa_kolor\";a:6:{s:4:\"name\";s:8:\"pa_kolor\";s:5:\"value\";s:0:\"\";s:8:\"position\";i:1;s:10:\"is_visible\";i:1;s:12:\"is_variation\";i:0;s:11:\"is_taxonomy\";i:1;}s:8:\"pa_fason\";a:6:{s:4:\"name\";s:8:\"pa_fason\";s:5:\"value\";s:0:\"\";s:8:\"position\";i:2;s:10:\"is_visible\";i:1;s:12:\"is_variation\";i:0;s:11:\"is_taxonomy\";i:1;}s:10:\"pa_dlugosc\";a:6:{s:4:\"name\";s:10:\"pa_dlugosc\";s:5:\"value\";s:0:\"\";s:8:\"position\";i:3;s:10:\"is_visible\";i:1;s:12:\"is_variation\";i:0;s:11:\"is_taxonomy\";i:1;}s:7:\"pa_wzor\";a:6:{s:4:\"name\";s:7:\"pa_wzor\";s:5:\"value\";s:0:\"\";s:8:\"position\";i:4;s:10:\"is_visible\";i:1;s:12:\"is_variation\";i:0;s:11:\"is_taxonomy\";i:1;}}"
            , response);
    }

    [Fact]
    public void CreateProductTaxonomy()
    {
        //Arrange
        var terms = new List<WpTerm>
        {
            new WpTerm { TermId = 1, Name = "Blog", Slug = "blog", TermGroup = 0},
            new WpTerm { TermId = 2, Name = "simple", Slug = "simple", TermGroup = 0},
            new WpTerm { TermId = 3, Name = "grouped", Slug = "grouped", TermGroup = 0},
            new WpTerm { TermId = 4, Name = "variable", Slug = "variable", TermGroup = 0},
            new WpTerm { TermId = 5, Name = "external", Slug = "external", TermGroup = 0},
            new WpTerm { TermId = 6, Name = "exclude-from-search", Slug = "exclude-from-search", TermGroup = 0},
            new WpTerm { TermId = 7, Name = "exclude-from-catalog", Slug = "exclude-from-catalog", TermGroup = 0},
            new WpTerm { TermId = 8, Name = "featured", Slug = "featured", TermGroup = 0},
            new WpTerm { TermId = 9, Name = "outofstock", Slug = "outofstock", TermGroup = 0},
            new WpTerm { TermId = 10, Name = "rated-1", Slug = "rated-1", TermGroup = 0},
            new WpTerm { TermId = 11, Name = "rated-2", Slug = "rated-2", TermGroup = 0},
            new WpTerm { TermId = 12, Name = "rated-3", Slug = "rated-3", TermGroup = 0},
            new WpTerm { TermId = 13, Name = "rated-4", Slug = "rated-4", TermGroup = 0},
            new WpTerm { TermId = 14, Name = "rated-5", Slug = "rated-5", TermGroup = 0},
            new WpTerm { TermId = 15, Name = "Nowości", Slug = "nowosci", TermGroup = 0},
            new WpTerm { TermId = 16, Name = "Sukienki", Slug = "sukienki", TermGroup = 0},
            new WpTerm { TermId = 17, Name = "Spodnie", Slug = "spodnie-damskie", TermGroup = 0},
            new WpTerm { TermId = 18, Name = "CategoriesFooterMenu", Slug = "categoriesfootermenu", TermGroup = 0},
            new WpTerm { TermId = 19, Name = "InformationFooterMenu", Slug = "informationfootermenu", TermGroup = 0},
            new WpTerm { TermId = 20, Name = "MyAccountFooterMenu", Slug = "myaccountfootermenu", TermGroup = 0},
            new WpTerm { TermId = 21, Name = "MainMenu", Slug = "mainmenu", TermGroup = 0},
            new WpTerm { TermId = 23, Name = "U", Slug = "u", TermGroup = 0},
            new WpTerm { TermId = 24, Name = "XS", Slug = "xs", TermGroup = 0},
            new WpTerm { TermId = 25, Name = "S", Slug = "s", TermGroup = 0},
            new WpTerm { TermId = 26, Name = "M", Slug = "m", TermGroup = 0},
            new WpTerm { TermId = 27, Name = "L", Slug = "l", TermGroup = 0},
            new WpTerm { TermId = 28, Name = "XL", Slug = "xl", TermGroup = 0},
            new WpTerm { TermId = 29, Name = "Biały", Slug = "bialy", TermGroup = 0},
            new WpTerm { TermId = 30, Name = "Czarny", Slug = "czarny", TermGroup = 0},
            new WpTerm { TermId = 31, Name = "Czerwony", Slug = "czerwony", TermGroup = 0},
            new WpTerm { TermId = 32, Name = "Niebieski", Slug = "niebieski", TermGroup = 0},
            new WpTerm { TermId = 33, Name = "Zielony", Slug = "zielony", TermGroup = 0},
            new WpTerm { TermId = 34, Name = "Żółty", Slug = "zolty", TermGroup = 0},
            new WpTerm { TermId = 36, Name = "Żółto-biała", Slug = "zolto-biala", TermGroup = 0},
            new WpTerm { TermId = 38, Name = "Dodatki", Slug = "dodatki", TermGroup = 0},
            new WpTerm { TermId = 40, Name = "Torebki handmade", Slug = "torebki-handmade", TermGroup = 0},
            new WpTerm { TermId = 41, Name = "Turkusowy", Slug = "turkusowy", TermGroup = 0},
            new WpTerm { TermId = 42, Name = "Brązowy", Slug = "brazowy", TermGroup = 0},
            new WpTerm { TermId = 43, Name = "Plecaki handmade", Slug = "plecaki-handmade", TermGroup = 0},
            new WpTerm { TermId = 44, Name = "Dresy", Slug = "dresy-damskie", TermGroup = 0},
            new WpTerm { TermId = 46, Name = "Bluzki", Slug = "bluzki-damskie", TermGroup = 0},
            new WpTerm { TermId = 47, Name = "Legginsy", Slug = "legginsy-damskie", TermGroup = 0},
            new WpTerm { TermId = 48, Name = "Spódnice", Slug = "spodnice-damskie", TermGroup = 0},
            new WpTerm { TermId = 49, Name = "Bluzy", Slug = "bluzy-damskie", TermGroup = 0},
            new WpTerm { TermId = 50, Name = "Ciemnozielony", Slug = "ciemnozielony", TermGroup = 0},
            new WpTerm { TermId = 51, Name = "S/M", Slug = "s-m", TermGroup = 0},
            new WpTerm { TermId = 52, Name = "L/XL", Slug = "l-xl", TermGroup = 0},
            new WpTerm { TermId = 53, Name = "Sukienki", Slug = "sukienki", TermGroup = 0},
            new WpTerm { TermId = 54, Name = "Kolekcja lato 2023", Slug = "kolekcja-lato-2023", TermGroup = 0},
            new WpTerm { TermId = 55, Name = "Sukienki", Slug = "sukienki", TermGroup = 0},
            new WpTerm { TermId = 56, Name = "Kolekcja lato 2023", Slug = "kolekcja-lato-2023", TermGroup = 0},
            new WpTerm { TermId = 57, Name = "XS/S", Slug = "xs-s", TermGroup = 0},
            new WpTerm { TermId = 58, Name = "M/L", Slug = "m-l", TermGroup = 0},
            new WpTerm { TermId = 59, Name = "XL/XXL", Slug = "xl-xxl", TermGroup = 0},
            new WpTerm { TermId = 60, Name = "3XL/4XL", Slug = "3xl-4xl", TermGroup = 0},
            new WpTerm { TermId = 61, Name = "5XL/6XL", Slug = "5xl-6xl", TermGroup = 0},
            new WpTerm { TermId = 62, Name = "Bordowy", Slug = "bordowy", TermGroup = 0},
            new WpTerm { TermId = 63, Name = "isdisabled", Slug = "isdisabled", TermGroup = 0},
            new WpTerm { TermId = 64, Name = "Sukienki mini", Slug = "sukienki-mini", TermGroup = 0},
            new WpTerm { TermId = 65, Name = "Sukienki z rozcięciem", Slug = "sukienki-z-rozcieciem", TermGroup = 0},
            new WpTerm { TermId = 66, Name = "Beżowy", Slug = "bezowy", TermGroup = 0},
            new WpTerm { TermId = 67, Name = "Różowy", Slug = "rozowy", TermGroup = 0},
            new WpTerm { TermId = 68, Name = "Bottega green", Slug = "bottega-green", TermGroup = 0},
            new WpTerm { TermId = 69, Name = "Granatowy", Slug = "granatowy", TermGroup = 0},
            new WpTerm { TermId = 70, Name = "Mocca", Slug = "mocca", TermGroup = 0},
            new WpTerm { TermId = 71, Name = "Szary", Slug = "szary", TermGroup = 0},
            new WpTerm { TermId = 72, Name = "Fioletowy", Slug = "fioletowy", TermGroup = 0},
            new WpTerm { TermId = 73, Name = "Jagodowy", Slug = "jagodowy", TermGroup = 0},
            new WpTerm { TermId = 74, Name = "Wrzosowy", Slug = "wrzosowy", TermGroup = 0},
            new WpTerm { TermId = 75, Name = "Kobaltowy", Slug = "kobaltowy", TermGroup = 0},
            new WpTerm { TermId = 76, Name = "Baby blue", Slug = "baby-blue", TermGroup = 0},
            new WpTerm { TermId = 77, Name = "Butelkowa zieleń", Slug = "bultekowa-zielen", TermGroup = 0},
            new WpTerm { TermId = 78, Name = "Khaki", Slug = "khaki", TermGroup = 0},
            new WpTerm { TermId = 79, Name = "Grafitowy", Slug = "grafitowy", TermGroup = 0},
            new WpTerm { TermId = 80, Name = "Srebrny", Slug = "srebrny", TermGroup = 0},
            new WpTerm { TermId = 81, Name = "Musztardowy", Slug = "musztardowy", TermGroup = 0},
            new WpTerm { TermId = 82, Name = "Morski", Slug = "morski", TermGroup = 0},
            new WpTerm { TermId = 83, Name = "Malinowy", Slug = "malinowy", TermGroup = 0},
            new WpTerm { TermId = 84, Name = "Ecru", Slug = "ecru", TermGroup = 0},
            new WpTerm { TermId = 85, Name = "Pomarańczowy", Slug = "pomaranczowy", TermGroup = 0},
            new WpTerm { TermId = 86, Name = "Brzoskwiniowy", Slug = "brzoskwiniowy", TermGroup = 0},
            new WpTerm { TermId = 87, Name = "Veri peri", Slug = "veri-peri", TermGroup = 0},
            new WpTerm { TermId = 88, Name = "Czekoladowy", Slug = "czekoladowy", TermGroup = 0},
            new WpTerm { TermId = 89, Name = "Fuksja", Slug = "fuksja", TermGroup = 0},
            new WpTerm { TermId = 90, Name = "Pudrowy róż", Slug = "pudrowy-roz", TermGroup = 0},
            new WpTerm { TermId = 91, Name = "Wielokolorowy", Slug = "wielokolorowy", TermGroup = 0},
            new WpTerm { TermId = 92, Name = "Miętowy", Slug = "mietowy", TermGroup = 0},
            new WpTerm { TermId = 93, Name = "Błękitny", Slug = "blekitny", TermGroup = 0},
            new WpTerm { TermId = 94, Name = "Amarantowy", Slug = "amarantowy", TermGroup = 0},
            new WpTerm { TermId = 95, Name = "Koralowy", Slug = "koralowy", TermGroup = 0},
            new WpTerm { TermId = 96, Name = "36", Slug = "36", TermGroup = 0},
            new WpTerm { TermId = 97, Name = "38", Slug = "38", TermGroup = 0},
            new WpTerm { TermId = 98, Name = "40", Slug = "40", TermGroup = 0},
            new WpTerm { TermId = 99, Name = "42", Slug = "42", TermGroup = 0},
            new WpTerm { TermId = 100, Name = "44", Slug = "44", TermGroup = 0},
            new WpTerm { TermId = 101, Name = "46", Slug = "46", TermGroup = 0},
            new WpTerm { TermId = 102, Name = "48", Slug = "48", TermGroup = 0},
            new WpTerm { TermId = 103, Name = "50", Slug = "50", TermGroup = 0},
            new WpTerm { TermId = 104, Name = "52", Slug = "52", TermGroup = 0},
            new WpTerm { TermId = 105, Name = "34", Slug = "34", TermGroup = 0},
            new WpTerm { TermId = 106, Name = "32", Slug = "32", TermGroup = 0},
            new WpTerm { TermId = 107, Name = "2XL", Slug = "2xl", TermGroup = 0},
            new WpTerm { TermId = 108, Name = "4XL", Slug = "4xl", TermGroup = 0},
            new WpTerm { TermId = 109, Name = "Długie", Slug = "dlugie", TermGroup = 0},
            new WpTerm { TermId = 110, Name = "Komplety", Slug = "komplety-damskie", TermGroup = 0},
            new WpTerm { TermId = 111, Name = "Góry", Slug = "gory", TermGroup = 0},
            new WpTerm { TermId = 112, Name = "Doły", Slug = "doly", TermGroup = 0},
            new WpTerm { TermId = 113, Name = "Bestsellery", Slug = "bestsellery", TermGroup = 0},
            new WpTerm { TermId = 114, Name = "Piżamy", Slug = "pizamy", TermGroup = 0},
            new WpTerm { TermId = 115, Name = "Jednokolorowe", Slug = "jednokolorowe", TermGroup = 0},
            new WpTerm { TermId = 116, Name = "Z kieszeniami", Slug = "z-kieszeniami", TermGroup = 0},
            new WpTerm { TermId = 117, Name = "Z kapturem", Slug = "z-kapturem", TermGroup = 0},
            new WpTerm { TermId = 118, Name = "Z długim rękawem", Slug = "z-dlugim-rekawem", TermGroup = 0},
            new WpTerm { TermId = 119, Name = "Welurowe", Slug = "welurowe", TermGroup = 0},
            new WpTerm { TermId = 120, Name = "Krótkie", Slug = "krotkie", TermGroup = 0},
            new WpTerm { TermId = 121, Name = "Pastelowe", Slug = "pastelowe", TermGroup = 0},
            new WpTerm { TermId = 122, Name = "Dopasowany", Slug = "dopasowany", TermGroup = 0},
            new WpTerm { TermId = 123, Name = "Mała czarna", Slug = "mala-czarna", TermGroup = 0},
            new WpTerm { TermId = 124, Name = "Eleganckie", Slug = "eleganckie", TermGroup = 0},
            new WpTerm { TermId = 125, Name = "Ołówkowe", Slug = "olowkowe", TermGroup = 0},
            new WpTerm { TermId = 126, Name = "Ze stójką", Slug = "ze-stojka", TermGroup = 0},
            new WpTerm { TermId = 127, Name = "Półgolf", Slug = "polgolf", TermGroup = 0},
            new WpTerm { TermId = 128, Name = "Mini", Slug = "mini", TermGroup = 0},
            new WpTerm { TermId = 129, Name = "Wzorzyste", Slug = "wzorzyste", TermGroup = 0},
            new WpTerm { TermId = 130, Name = "W kwiaty", Slug = "w-kwiaty", TermGroup = 0},
            new WpTerm { TermId = 131, Name = "Boho", Slug = "boho", TermGroup = 0},
            new WpTerm { TermId = 132, Name = "Rozkloszowane", Slug = "rozkloszowane", TermGroup = 0},
            new WpTerm { TermId = 133, Name = "Z falbaną", Slug = "z-falbana", TermGroup = 0},
            new WpTerm { TermId = 134, Name = "Na ramiączkach", Slug = "na-ramiaczkach", TermGroup = 0},
            new WpTerm { TermId = 135, Name = "Luźny", Slug = "luzny", TermGroup = 0},
            new WpTerm { TermId = 136, Name = "Midi", Slug = "midi", TermGroup = 0},
            new WpTerm { TermId = 137, Name = "Maxi", Slug = "maxi", TermGroup = 0},
            new WpTerm { TermId = 138, Name = "Z krótkim rękawem", Slug = "z-krotkim-rekawem", TermGroup = 0},
            new WpTerm { TermId = 139, Name = "Szorty", Slug = "szorty-damskie", TermGroup = 0},
            new WpTerm { TermId = 140, Name = "Z wysokim stanem", Slug = "z-wysokim-stanem", TermGroup = 0},
            new WpTerm { TermId = 141, Name = "Wieczorowe", Slug = "wieczorowe", TermGroup = 0},
            new WpTerm { TermId = 142, Name = "Bez pleców", Slug = "bez-plecow", TermGroup = 0},
            new WpTerm { TermId = 143, Name = "Z siateczką", Slug = "z-siateczka", TermGroup = 0},
            new WpTerm { TermId = 144, Name = "W kropki", Slug = "w-kropki", TermGroup = 0},
            new WpTerm { TermId = 145, Name = "Z prostymi nogawkami", Slug = "z-prostymi-nogawkami", TermGroup = 0},
            new WpTerm { TermId = 146, Name = "Panterka", Slug = "panterka", TermGroup = 0},
            new WpTerm { TermId = 147, Name = "Zwierzęce", Slug = "zwierzece", TermGroup = 0},
            new WpTerm { TermId = 148, Name = "Klasyczne", Slug = "klasyczne", TermGroup = 0},
            new WpTerm { TermId = 149, Name = "Wizytowe", Slug = "wizytowe", TermGroup = 0},
            new WpTerm { TermId = 150, Name = "Nogawki 7/8", Slug = "nogawki-7-8", TermGroup = 0},
            new WpTerm { TermId = 151, Name = "Długie", Slug = "dlugie", TermGroup = 0},
            new WpTerm { TermId = 152, Name = "Oversize", Slug = "oversize", TermGroup = 0},
            new WpTerm { TermId = 153, Name = "Z szerokimi nogawkami", Slug = "z-szerokimi-nogawkami", TermGroup = 0},
            new WpTerm { TermId = 154, Name = "Sukienki z wycięciem na plecach", Slug = "sukienki-z-wycieciem-na-plecach", TermGroup = 0},
            new WpTerm { TermId = 155, Name = "Midi", Slug = "midi", TermGroup = 0},
        };

        var termTaxonomy = new List<WpTermTaxonomy>
        {
            new WpTermTaxonomy { TermTaxonomyId = 1, TermId = 1, Taxonomy = "category" },
            new WpTermTaxonomy { TermTaxonomyId = 2, TermId = 2, Taxonomy = "product_type" },
            new WpTermTaxonomy { TermTaxonomyId = 3, TermId = 3, Taxonomy = "product_type" },
            new WpTermTaxonomy { TermTaxonomyId = 4, TermId = 4, Taxonomy = "product_type" },
            new WpTermTaxonomy { TermTaxonomyId = 5, TermId = 5, Taxonomy = "product_type" },
            new WpTermTaxonomy { TermTaxonomyId = 6, TermId = 6, Taxonomy = "product_visibility" },
            new WpTermTaxonomy { TermTaxonomyId = 7, TermId = 7, Taxonomy = "product_visibility" },
            new WpTermTaxonomy { TermTaxonomyId = 8, TermId = 8, Taxonomy = "product_visibility" },
            new WpTermTaxonomy { TermTaxonomyId = 9, TermId = 9, Taxonomy = "product_visibility" },
            new WpTermTaxonomy { TermTaxonomyId = 10, TermId = 10, Taxonomy = "product_visibility" },
            new WpTermTaxonomy { TermTaxonomyId = 11, TermId = 11, Taxonomy = "product_visibility" },
            new WpTermTaxonomy { TermTaxonomyId = 12, TermId = 12, Taxonomy = "product_visibility" },
            new WpTermTaxonomy { TermTaxonomyId = 13, TermId = 13, Taxonomy = "product_visibility" },
            new WpTermTaxonomy { TermTaxonomyId = 14, TermId = 14, Taxonomy = "product_visibility" },
            new WpTermTaxonomy { TermTaxonomyId = 15, TermId = 15, Taxonomy = "product_cat" },
            new WpTermTaxonomy { TermTaxonomyId = 16, TermId = 16, Taxonomy = "product_cat" },
            new WpTermTaxonomy { TermTaxonomyId = 17, TermId = 17, Taxonomy = "product_cat" },
            new WpTermTaxonomy { TermTaxonomyId = 18, TermId = 18, Taxonomy = "nav_menu" },
            new WpTermTaxonomy { TermTaxonomyId = 19, TermId = 19, Taxonomy = "nav_menu" },
            new WpTermTaxonomy { TermTaxonomyId = 20, TermId = 20, Taxonomy = "nav_menu" },
            new WpTermTaxonomy { TermTaxonomyId = 21, TermId = 21, Taxonomy = "nav_menu" },
            new WpTermTaxonomy { TermTaxonomyId = 23, TermId = 23, Taxonomy = "pa_rozmiar" },
            new WpTermTaxonomy { TermTaxonomyId = 24, TermId = 24, Taxonomy = "pa_rozmiar" },
            new WpTermTaxonomy { TermTaxonomyId = 25, TermId = 25, Taxonomy = "pa_rozmiar" },
            new WpTermTaxonomy { TermTaxonomyId = 26, TermId = 26, Taxonomy = "pa_rozmiar" },
            new WpTermTaxonomy { TermTaxonomyId = 27, TermId = 27, Taxonomy = "pa_rozmiar" },
            new WpTermTaxonomy { TermTaxonomyId = 28, TermId = 28, Taxonomy = "pa_rozmiar" },
            new WpTermTaxonomy { TermTaxonomyId = 29, TermId = 29, Taxonomy = "pa_kolor" },
            new WpTermTaxonomy { TermTaxonomyId = 30, TermId = 30, Taxonomy = "pa_kolor" },
            new WpTermTaxonomy { TermTaxonomyId = 31, TermId = 31, Taxonomy = "pa_kolor" },
            new WpTermTaxonomy { TermTaxonomyId = 32, TermId = 32, Taxonomy = "pa_kolor" },
            new WpTermTaxonomy { TermTaxonomyId = 33, TermId = 33, Taxonomy = "pa_kolor" },
            new WpTermTaxonomy { TermTaxonomyId = 34, TermId = 34, Taxonomy = "pa_kolor" },
            new WpTermTaxonomy { TermTaxonomyId = 36, TermId = 36, Taxonomy = "pa_kolor" },
            new WpTermTaxonomy { TermTaxonomyId = 38, TermId = 38, Taxonomy = "product_cat" },
            new WpTermTaxonomy { TermTaxonomyId = 40, TermId = 40, Taxonomy = "product_cat" },
            new WpTermTaxonomy { TermTaxonomyId = 41, TermId = 41, Taxonomy = "pa_kolor" },
            new WpTermTaxonomy { TermTaxonomyId = 42, TermId = 42, Taxonomy = "pa_kolor" },
            new WpTermTaxonomy { TermTaxonomyId = 43, TermId = 43, Taxonomy = "product_cat" },
            new WpTermTaxonomy { TermTaxonomyId = 44, TermId = 44, Taxonomy = "product_cat" },
            new WpTermTaxonomy { TermTaxonomyId = 46, TermId = 46, Taxonomy = "product_cat" },
            new WpTermTaxonomy { TermTaxonomyId = 47, TermId = 47, Taxonomy = "product_cat" },
            new WpTermTaxonomy { TermTaxonomyId = 48, TermId = 48, Taxonomy = "product_cat" },
            new WpTermTaxonomy { TermTaxonomyId = 49, TermId = 49, Taxonomy = "product_cat" },
            new WpTermTaxonomy { TermTaxonomyId = 50, TermId = 50, Taxonomy = "pa_kolor" },
            new WpTermTaxonomy { TermTaxonomyId = 51, TermId = 51, Taxonomy = "pa_rozmiar" },
            new WpTermTaxonomy { TermTaxonomyId = 52, TermId = 52, Taxonomy = "pa_rozmiar" },
            new WpTermTaxonomy { TermTaxonomyId = 53, TermId = 53, Taxonomy = "post_tag" },
            new WpTermTaxonomy { TermTaxonomyId = 54, TermId = 54, Taxonomy = "post_tag" },
            new WpTermTaxonomy { TermTaxonomyId = 55, TermId = 55, Taxonomy = "product_tag" },
            new WpTermTaxonomy { TermTaxonomyId = 56, TermId = 56, Taxonomy = "product_tag" },
            new WpTermTaxonomy { TermTaxonomyId = 57, TermId = 57, Taxonomy = "pa_rozmiar" },
            new WpTermTaxonomy { TermTaxonomyId = 58, TermId = 58, Taxonomy = "pa_rozmiar" },
            new WpTermTaxonomy { TermTaxonomyId = 59, TermId = 59, Taxonomy = "pa_rozmiar" },
            new WpTermTaxonomy { TermTaxonomyId = 60, TermId = 60, Taxonomy = "pa_rozmiar" },
            new WpTermTaxonomy { TermTaxonomyId = 61, TermId = 61, Taxonomy = "pa_rozmiar" },
            new WpTermTaxonomy { TermTaxonomyId = 62, TermId = 62, Taxonomy = "pa_kolor" },
            new WpTermTaxonomy { TermTaxonomyId = 63, TermId = 63, Taxonomy = "berocket_taxonomy_data" },
            new WpTermTaxonomy { TermTaxonomyId = 64, TermId = 64, Taxonomy = "pa_kroj-sukienki" },
            new WpTermTaxonomy { TermTaxonomyId = 65, TermId = 65, Taxonomy = "pa_kroj-sukienki" },
            new WpTermTaxonomy { TermTaxonomyId = 66, TermId = 66, Taxonomy = "pa_kolor" },
            new WpTermTaxonomy { TermTaxonomyId = 67, TermId = 67, Taxonomy = "pa_kolor" },
            new WpTermTaxonomy { TermTaxonomyId = 68, TermId = 68, Taxonomy = "pa_kolor" },
            new WpTermTaxonomy { TermTaxonomyId = 69, TermId = 69, Taxonomy = "pa_kolor" },
            new WpTermTaxonomy { TermTaxonomyId = 70, TermId = 70, Taxonomy = "pa_kolor" },
            new WpTermTaxonomy { TermTaxonomyId = 71, TermId = 71, Taxonomy = "pa_kolor" },
            new WpTermTaxonomy { TermTaxonomyId = 72, TermId = 72, Taxonomy = "pa_kolor" },
            new WpTermTaxonomy { TermTaxonomyId = 73, TermId = 73, Taxonomy = "pa_kolor" },
            new WpTermTaxonomy { TermTaxonomyId = 74, TermId = 74, Taxonomy = "pa_kolor" },
            new WpTermTaxonomy { TermTaxonomyId = 75, TermId = 75, Taxonomy = "pa_kolor" },
            new WpTermTaxonomy { TermTaxonomyId = 76, TermId = 76, Taxonomy = "pa_kolor" },
            new WpTermTaxonomy { TermTaxonomyId = 77, TermId = 77, Taxonomy = "pa_kolor" },
            new WpTermTaxonomy { TermTaxonomyId = 78, TermId = 78, Taxonomy = "pa_kolor" },
            new WpTermTaxonomy { TermTaxonomyId = 79, TermId = 79, Taxonomy = "pa_kolor" },
            new WpTermTaxonomy { TermTaxonomyId = 80, TermId = 80, Taxonomy = "pa_kolor" },
            new WpTermTaxonomy { TermTaxonomyId = 81, TermId = 81, Taxonomy = "pa_kolor" },
            new WpTermTaxonomy { TermTaxonomyId = 82, TermId = 82, Taxonomy = "pa_kolor" },
            new WpTermTaxonomy { TermTaxonomyId = 83, TermId = 83, Taxonomy = "pa_kolor" },
            new WpTermTaxonomy { TermTaxonomyId = 84, TermId = 84, Taxonomy = "pa_kolor" },
            new WpTermTaxonomy { TermTaxonomyId = 85, TermId = 85, Taxonomy = "pa_kolor" },
            new WpTermTaxonomy { TermTaxonomyId = 86, TermId = 86, Taxonomy = "pa_kolor" },
            new WpTermTaxonomy { TermTaxonomyId = 87, TermId = 87, Taxonomy = "pa_kolor" },
            new WpTermTaxonomy { TermTaxonomyId = 88, TermId = 88, Taxonomy = "pa_kolor" },
            new WpTermTaxonomy { TermTaxonomyId = 89, TermId = 89, Taxonomy = "pa_kolor" },
            new WpTermTaxonomy { TermTaxonomyId = 90, TermId = 90, Taxonomy = "pa_kolor" },
            new WpTermTaxonomy { TermTaxonomyId = 91, TermId = 91, Taxonomy = "pa_kolor" },
            new WpTermTaxonomy { TermTaxonomyId = 92, TermId = 92, Taxonomy = "pa_kolor" },
            new WpTermTaxonomy { TermTaxonomyId = 93, TermId = 93, Taxonomy = "pa_kolor" },
            new WpTermTaxonomy { TermTaxonomyId = 94, TermId = 94, Taxonomy = "pa_kolor" },
            new WpTermTaxonomy { TermTaxonomyId = 95, TermId = 95, Taxonomy = "pa_kolor" },
            new WpTermTaxonomy { TermTaxonomyId = 96, TermId = 96, Taxonomy = "pa_rozmiar" },
            new WpTermTaxonomy { TermTaxonomyId = 97, TermId = 97, Taxonomy = "pa_rozmiar" },
            new WpTermTaxonomy { TermTaxonomyId = 98, TermId = 98, Taxonomy = "pa_rozmiar" },
            new WpTermTaxonomy { TermTaxonomyId = 99, TermId = 99, Taxonomy = "pa_rozmiar" },
            new WpTermTaxonomy { TermTaxonomyId = 100, TermId = 100, Taxonomy = "pa_rozmiar" },
            new WpTermTaxonomy { TermTaxonomyId = 101, TermId = 101, Taxonomy = "pa_rozmiar" },
            new WpTermTaxonomy { TermTaxonomyId = 102, TermId = 102, Taxonomy = "pa_rozmiar" },
            new WpTermTaxonomy { TermTaxonomyId = 103, TermId = 103, Taxonomy = "pa_rozmiar" },
            new WpTermTaxonomy { TermTaxonomyId = 104, TermId = 104, Taxonomy = "pa_rozmiar" },
            new WpTermTaxonomy { TermTaxonomyId = 105, TermId = 105, Taxonomy = "pa_rozmiar" },
            new WpTermTaxonomy { TermTaxonomyId = 106, TermId = 106, Taxonomy = "pa_rozmiar" },
            new WpTermTaxonomy { TermTaxonomyId = 107, TermId = 107, Taxonomy = "pa_rozmiar" },
            new WpTermTaxonomy { TermTaxonomyId = 108, TermId = 108, Taxonomy = "pa_rozmiar" },
            new WpTermTaxonomy { TermTaxonomyId = 109, TermId = 109, Taxonomy = "pa_dlugosc" },
            new WpTermTaxonomy { TermTaxonomyId = 110, TermId = 110, Taxonomy = "product_cat" },
            new WpTermTaxonomy { TermTaxonomyId = 111, TermId = 111, Taxonomy = "product_cat" },
            new WpTermTaxonomy { TermTaxonomyId = 112, TermId = 112, Taxonomy = "product_cat" },
            new WpTermTaxonomy { TermTaxonomyId = 113, TermId = 113, Taxonomy = "product_cat" },
            new WpTermTaxonomy { TermTaxonomyId = 114, TermId = 114, Taxonomy = "product_cat" },
            new WpTermTaxonomy { TermTaxonomyId = 115, TermId = 115, Taxonomy = "pa_wzor" },
            new WpTermTaxonomy { TermTaxonomyId = 116, TermId = 116, Taxonomy = "pa_fason" },
            new WpTermTaxonomy { TermTaxonomyId = 117, TermId = 117, Taxonomy = "pa_fason" },
            new WpTermTaxonomy { TermTaxonomyId = 118, TermId = 118, Taxonomy = "pa_fason" },
            new WpTermTaxonomy { TermTaxonomyId = 119, TermId = 119, Taxonomy = "pa_wzor" },
            new WpTermTaxonomy { TermTaxonomyId = 120, TermId = 120, Taxonomy = "pa_dlugosc" },
            new WpTermTaxonomy { TermTaxonomyId = 121, TermId = 121, Taxonomy = "pa_wzor" },
            new WpTermTaxonomy { TermTaxonomyId = 122, TermId = 122, Taxonomy = "pa_fason" },
            new WpTermTaxonomy { TermTaxonomyId = 123, TermId = 123, Taxonomy = "pa_fason" },
            new WpTermTaxonomy { TermTaxonomyId = 124, TermId = 124, Taxonomy = "pa_fason" },
            new WpTermTaxonomy { TermTaxonomyId = 125, TermId = 125, Taxonomy = "pa_fason" },
            new WpTermTaxonomy { TermTaxonomyId = 126, TermId = 126, Taxonomy = "pa_fason" },
            new WpTermTaxonomy { TermTaxonomyId = 127, TermId = 127, Taxonomy = "pa_fason" },
            new WpTermTaxonomy { TermTaxonomyId = 128, TermId = 128, Taxonomy = "pa_dlugosc" },
            new WpTermTaxonomy { TermTaxonomyId = 129, TermId = 129, Taxonomy = "pa_wzor" },
            new WpTermTaxonomy { TermTaxonomyId = 130, TermId = 130, Taxonomy = "pa_wzor" },
            new WpTermTaxonomy { TermTaxonomyId = 131, TermId = 131, Taxonomy = "pa_fason" },
            new WpTermTaxonomy { TermTaxonomyId = 132, TermId = 132, Taxonomy = "pa_fason" },
            new WpTermTaxonomy { TermTaxonomyId = 133, TermId = 133, Taxonomy = "pa_fason" },
            new WpTermTaxonomy { TermTaxonomyId = 134, TermId = 134, Taxonomy = "pa_fason" },
            new WpTermTaxonomy { TermTaxonomyId = 135, TermId = 135, Taxonomy = "pa_fason" },
            new WpTermTaxonomy { TermTaxonomyId = 136, TermId = 136, Taxonomy = "pa_dlugosc" },
            new WpTermTaxonomy { TermTaxonomyId = 137, TermId = 137, Taxonomy = "pa_dlugosc" },
            new WpTermTaxonomy { TermTaxonomyId = 138, TermId = 138, Taxonomy = "pa_fason" },
            new WpTermTaxonomy { TermTaxonomyId = 139, TermId = 139, Taxonomy = "product_cat" },
            new WpTermTaxonomy { TermTaxonomyId = 140, TermId = 140, Taxonomy = "pa_fason" },
            new WpTermTaxonomy { TermTaxonomyId = 141, TermId = 141, Taxonomy = "pa_fason" },
            new WpTermTaxonomy { TermTaxonomyId = 142, TermId = 142, Taxonomy = "pa_fason" },
            new WpTermTaxonomy { TermTaxonomyId = 143, TermId = 143, Taxonomy = "pa_wzor" },
            new WpTermTaxonomy { TermTaxonomyId = 144, TermId = 144, Taxonomy = "pa_wzor" },
            new WpTermTaxonomy { TermTaxonomyId = 145, TermId = 145, Taxonomy = "pa_fason" },
            new WpTermTaxonomy { TermTaxonomyId = 146, TermId = 146, Taxonomy = "pa_kolor" },
            new WpTermTaxonomy { TermTaxonomyId = 147, TermId = 147, Taxonomy = "pa_wzor" },
            new WpTermTaxonomy { TermTaxonomyId = 148, TermId = 148, Taxonomy = "pa_fason" },
            new WpTermTaxonomy { TermTaxonomyId = 149, TermId = 149, Taxonomy = "pa_fason" },
            new WpTermTaxonomy { TermTaxonomyId = 150, TermId = 150, Taxonomy = "pa_dlugosc" },
            new WpTermTaxonomy { TermTaxonomyId = 151, TermId = 151, Taxonomy = "pa_fason" },
            new WpTermTaxonomy { TermTaxonomyId = 152, TermId = 152, Taxonomy = "pa_fason" },
            new WpTermTaxonomy { TermTaxonomyId = 153, TermId = 153, Taxonomy = "pa_fason" },
            new WpTermTaxonomy { TermTaxonomyId = 154, TermId = 154, Taxonomy = "pa_kroj-sukienki" },
            new WpTermTaxonomy { TermTaxonomyId = 155, TermId = 155, Taxonomy = "pa_fason" },
        };

        var parentProductDto = new WpPostDto(
            "BORDOWY",
            null,
            "z kieszeniami,z kapturem",
            "długie",
            "jednokolorowe"
        );

        var variantProducDtos = new List<WpPostDto>
        {
            new WpPostDto(null, "XS/S", null, null, null),
            new WpPostDto(null, "M/L", null, null, null),
            new WpPostDto(null, "XL/XXL", null, null, null),
            new WpPostDto(null, "3XL/4XL", null, null, null),
            new WpPostDto(null, "5XL/6XL", null, null, null),
        };

        //Act
        var response = _sut.MapParentProductTaxonomyValues(1, parentProductDto, variantProducDtos, terms);

        //Assert
        Assert.NotNull(response);
    }
}
